name: hn_app
description: A new Flutter application.

version: 0.2.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  url_launcher: "5.1.4"
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  built_collection: 4.2.2
  built_value: 6.7.1

dev_dependencies:
  build_runner: 1.7.1
  built_value_generator: 6.7.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
